using System;

namespace GdNet.Layers.Dtos
{
    public abstract class EntityDtoT<TId> where TId : new()
    {
        public TId Id { get; set; }

        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// An unique id which will be generated by application worker
        /// </summary>
        public string FriendlyId
        {
            get;
            set;
        }

        public string CreatedBy { get; set; }

        public string Note { get; set; }
    }
}